<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.12.5 on win32)" generated="2025-04-16T12:48:35.334352" rpa="false" schemaversion="5">
<suite id="s1" name="MisesAJourAndReseau" source="C:\Users\bahae\Desktop\PfeProject\test_cases\MisesAJourAndReseau.robot">
<kw name="DÃ©marrer Driver" type="SETUP">
<kw name="Setup Driver" owner="Integration">
<msg time="2025-04-16T12:49:06.318792" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
    at getResponseForW3CError (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)</msg>
<var>${driver}</var>
<arg>${Device}</arg>
<doc>Initialise et retourne le driver Appium.</doc>
<status status="FAIL" start="2025-04-16T12:48:35.616353" elapsed="30.704439">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
    at getResponseForW3CError (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)</status>
</kw>
<kw name="Set Suite Variable" owner="BuiltIn">
<arg>${driver}</arg>
<doc>Makes a variable available everywhere within the scope of the current suite.</doc>
<status status="NOT RUN" start="2025-04-16T12:49:06.320792" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2025-04-16T12:48:35.616353" elapsed="30.705438">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
    at getResponseForW3CError (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)</status>
</kw>
<test id="s1-t1" name="Test Verfier Mise A Jour System" line="29">
<status status="FAIL" start="2025-04-16T12:49:06.321791" elapsed="0.000000">Parent suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
    at getResponseForW3CError (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)</status>
</test>
<kw name="Fermer Driver" type="TEARDOWN">
<kw name="Close Driver" owner="Integration">
<msg time="2025-04-16T12:49:06.322792" level="FAIL">Variable '${driver}' not found.</msg>
<arg>${driver}</arg>
<doc>Ferme proprement le driver Appium.</doc>
<status status="FAIL" start="2025-04-16T12:49:06.322792" elapsed="0.000000">Variable '${driver}' not found.</status>
</kw>
<status status="FAIL" start="2025-04-16T12:49:06.322792" elapsed="0.000000">Variable '${driver}' not found.</status>
</kw>
<status status="FAIL" start="2025-04-16T12:48:35.336354" elapsed="30.986438">Suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms
    at getResponseForW3CError (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)

Also suite teardown failed:
Variable '${driver}' not found.</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="MisesAJourAndReseau" id="s1" pass="0" fail="1" skip="0">MisesAJourAndReseau</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
