<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.12.5 on win32)" generated="2025-05-05T17:32:52.676947" rpa="false" schemaversion="5">
<suite id="s1" name="MisesAJourAndReseau" source="C:\Users\bahae\Desktop\PfeProject\test_cases\MisesAJourAndReseau.robot">
<kw name="Démarrer Driver" type="SETUP">
<kw name="Setup Driver" owner="Integration">
<msg time="2025-05-05T17:33:06.136579" level="INFO">${driver} = &lt;appium.webdriver.webdriver.WebDriver (session="9bc92f83-4088-4cf7-936e-6041a4a6a83c")&gt;</msg>
<var>${driver}</var>
<arg>${Device}</arg>
<doc>Initialise et retourne le driver Appium.</doc>
<status status="PASS" start="2025-05-05T17:32:53.195926" elapsed="12.940653"/>
</kw>
<kw name="Set Suite Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.137631" level="INFO">${driver} = &lt;appium.webdriver.webdriver.WebDriver (session="9bc92f83-4088-4cf7-936e-6041a4a6a83c")&gt;</msg>
<arg>${driver}</arg>
<doc>Makes a variable available everywhere within the scope of the current suite.</doc>
<status status="PASS" start="2025-05-05T17:33:06.137631" elapsed="0.000000"/>
</kw>
<status status="PASS" start="2025-05-05T17:32:53.195926" elapsed="12.941705"/>
</kw>
<test id="s1-t1" name="Test Verfier Mise A Jour System" line="32">
<kw name="Get System Language" owner="Integration">
<msg time="2025-05-05T17:33:06.191053" level="INFO">${lang} = fr</msg>
<var>${lang}</var>
<arg>${Device}</arg>
<status status="PASS" start="2025-05-05T17:33:06.137631" elapsed="0.053422"/>
</kw>
<if>
<branch type="IF" condition="'${lang}' == 'fr'">
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.191053" level="INFO">${System} = Système</msg>
<var>${System}</var>
<arg>Système</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-05-05T17:33:06.191053" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.191053" level="INFO">${Setting} = Paramètres</msg>
<var>${Setting}</var>
<arg>Paramètres</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-05-05T17:33:06.191053" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.191053" level="INFO">${Date} = Date et heure</msg>
<var>${Date}</var>
<arg>Date et heure</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-05-05T17:33:06.191053" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.192075" level="INFO">${Btn_Heure} = Définir l'heure</msg>
<var>${Btn_Heure}</var>
<arg>Définir l'heure</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.192075" level="INFO">${System_update} = System update</msg>
<var>${System_update}</var>
<arg>System update</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-05-05T17:33:06.192075" level="INFO">${System_update_check} = Check for update</msg>
<var>${System_update_check}</var>
<arg>Check for update</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<status status="PASS" start="2025-05-05T17:33:06.191053" elapsed="0.001022"/>
</branch>
<branch type="ELSE">
<kw name="Set Variable" owner="BuiltIn">
<var>${System}</var>
<arg>System</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<var>${Setting}</var>
<arg>Settings</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<var>${Date}</var>
<arg>Date &amp; time</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<var>${Btn_Heure}</var>
<arg>Définir l'heure</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<var>${System_update}</var>
<arg>System update</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<kw name="Set Variable" owner="BuiltIn">
<var>${System_update_check}</var>
<arg>Check for update</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</kw>
<status status="NOT RUN" start="2025-05-05T17:33:06.192075" elapsed="0.000000"/>
</branch>
<status status="PASS" start="2025-05-05T17:33:06.191053" elapsed="0.002000"/>
</if>
<kw name="Open Application With Click" owner="Integration">
<msg time="2025-05-05T17:33:16.696672" level="INFO">Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: read ECONNRESET
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: read ECONNRESET
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a1/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a1/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a2/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a2/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a3/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a3/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016aa/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016aa/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ab/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ab/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ac/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ac/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b3/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b3/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b4/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b4/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b5/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b5/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016bc/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016bc/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016bd/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016bd/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016be/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016be/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c5/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c5/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c6/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c6/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c7/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c7/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a4/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a4/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a5/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a5/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a6/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016a6/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ad/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ad/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ae/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ae/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016af/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016af/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b6/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b6/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b7/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b7/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b8/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016b8/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016bf/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016bf/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c0/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c0/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c1/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c1/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c8/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c8/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c9/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016c9/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ca/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff000016ca/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)
Erreur lors de la récupération d'un élément : Message: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff0000169a/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /element/00000000-0000-0229-ffff-ffff0000169a/attribute/class' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.getAttribute (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\element.js:26:5)

📌 Liste des applications détectées : ['Agenda', 'Appium Settings', 'ARD Audiothek', 'Audio Bluetooth']
📌 First Home Page détectée : ['Agenda', 'Appium Settings', 'ARD Audiothek', 'Audio Bluetooth']</msg>
<msg time="2025-05-05T17:33:16.697672" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /actions' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /actions' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.performActions (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\actions.js:88:3)</msg>
<var>${resultat}</var>
<arg>${driver}</arg>
<arg>${Setting}</arg>
<status status="FAIL" start="2025-05-05T17:33:06.193053" elapsed="10.511626">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /actions' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /actions' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.performActions (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\actions.js:88:3)</status>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>1s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2025-05-05T17:33:16.705673" elapsed="0.000000"/>
</kw>
<kw name="Clique Sur Setting" owner="Integration">
<arg>${driver}</arg>
<arg>${System}</arg>
<arg>${Setting_menu}</arg>
<status status="NOT RUN" start="2025-05-05T17:33:16.705673" elapsed="0.000000"/>
</kw>
<kw name="Clique Sur Setting Include" owner="Integration">
<arg>${driver}</arg>
<arg>${System_update}</arg>
<arg>${Setting_system}</arg>
<status status="NOT RUN" start="2025-05-05T17:33:16.705673" elapsed="0.000000"/>
</kw>
<kw name="Click Element By Text" owner="Integration">
<arg>${driver}</arg>
<arg>${System_update_check}</arg>
<status status="NOT RUN" start="2025-05-05T17:33:16.705673" elapsed="0.000000"/>
</kw>
<doc>Verifies system update functionality
- Navigates to system update section
- Checks for available updates
- Supports both French and English interfaces</doc>
<status status="FAIL" start="2025-05-05T17:33:06.137631" elapsed="10.569041">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /actions' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /actions' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
    at UIA2Proxy.command (C:\Users\bahae\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.performActions (C:\Users\bahae\.appium\node_modules\appium-uiautomator2-driver\lib\commands\actions.js:88:3)</status>
</test>
<kw name="Fermer Driver" type="TEARDOWN">
<kw name="Close Driver" owner="Integration">
<msg time="2025-05-05T17:33:17.447548" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None)': /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c</msg>
<msg time="2025-05-05T17:33:19.483334" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF932C0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c</msg>
<msg time="2025-05-05T17:33:21.523885" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF92F00&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c</msg>
<msg time="2025-05-05T17:33:23.550654" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF925A0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</msg>
<arg>${driver}</arg>
<doc>Ferme proprement le driver Appium.</doc>
<status status="FAIL" start="2025-05-05T17:33:16.706672" elapsed="6.865014">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF925A0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</kw>
<status status="FAIL" start="2025-05-05T17:33:16.706672" elapsed="6.865014">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF925A0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</kw>
<doc>Tests for system update verification
- Verifies system update functionality
- Supports both French and English interfaces</doc>
<status status="FAIL" start="2025-05-05T17:32:52.677983" elapsed="30.893703">Suite teardown failed:
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF925A0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="MisesAJourAndReseau" id="s1" pass="0" fail="1" skip="0">MisesAJourAndReseau</stat>
</suite>
</statistics>
<errors>
<msg time="2025-05-05T17:33:17.447548" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None)': /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c</msg>
<msg time="2025-05-05T17:33:19.483334" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF932C0&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c</msg>
<msg time="2025-05-05T17:33:21.523885" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002E64FF92F00&gt;: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/9bc92f83-4088-4cf7-936e-6041a4a6a83c</msg>
</errors>
</robot>
